<?php
/**
 * Space48_ProductAvailability
 *
 * @category    Space48
 * @package     Space48_ProductAvailability
 * @Date        03/2017
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      @diazwatson
 */
?>
<?php /** @var $block \Space48\ProductAvailability\Block\Catalog\Product\ListProduct */ ?>
<?php $_product = $block->getProduct(); ?>
<?php if (!$_product->isAvailable() || $block->isDebugMode()) : ?>
    <? echo $block->getAvailability($_product) ?>
<?php endif; ?>
