<?php
/**
 * Space48_ProductAvailability
 *
 * @category    Space48
 * @package     Space48_ProductAvailability
 * @Date        03/2017
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      @diazwatson
 */
?>
<?php /** @var $block \Space48\ProductAvailability\Block\Catalog\Product\ListProduct */ ?>
<?php $product = $block->getProduct(); ?>
<?php if (!$block->isInStock($product) || $block->isDebugMode()) : ?>
    <?php echo $block->getAvailabilityMessage($product) ?>
<?php endif; ?>
