<?php
/**
 * Space48_ProductAvailability
 *
 * @category    Space48
 * @package     Space48_ProductAvailability
 * @Date        03/2017
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      @diazwatson
 */

// @codingStandardsIgnoreFile

?>
<?php /* @var $block \Magento\Catalog\Block\Product\View\AbstractView */?>
<?php $_product = $block->getProduct() ?>
<?php $availability = $block->getAvailability($_product); ?>
<?php if ($block->displayProductStockStatus()): ?>
    <div class="stock <?= $availability['class'] ?>" title="<?php echo __('Availability') ?>">
        <span><?php echo __('Availability:') ?></span>
        <span class="stock-text"><?= $availability['label'] ?></span>
    </div>
<?php endif; ?>
