<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable() && $block->showAddToCartButtonAfterPreSellCheck()): ?>
    <div class="box-tocart">
        <div class="fieldset">
            <?php if ($block->shouldRenderQuantity()): ?>
                <div class="quantity-selector js-quantity-selector">
                    <div class="field qty">
                        <label class="label" for="qty"><span><?php /* @escapeNotVerified */ echo __('Qty') ?></span></label>
                        <div class="control">
                            <input type="number"
                                   name="qty"
                                   id="qty"
                                   maxlength="12"
                                   value="<?php /* @escapeNotVerified */ echo $block->getProductDefaultQty() * 1 ?>"
                                   title="<?php /* @escapeNotVerified */ echo __('Qty') ?>" class="input-text qty"
                                   data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                            />
                        </div>
                    </div>
                    <button type="button" name="qty-minus" class="quantity-selector__minus js-qty-minus">-</button>
                    <button type="button" name="qty-plus" class="quantity-selector__plus js-qty-plus">+</button>
                    <div class="quantity-selector__info">
                <span>
                    <?php /* @escapeNotVerified */ echo __('Qty:') ?>
                    <span class="js-qty-text"><?php /* @escapeNotVerified */ echo $block->getProductDefaultQty() * 1 ?></span>
                </span>
                    </div>
                </div>
            <?php endif; ?>
            <div class="actions">
                <button type="submit"
                        title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
                        class="action primary tocart"
                        id="product-addtocart-button">
                    <span><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>
                </button>
                <?php echo $block->getChildHtml('', true) ?>
            </div>
        </div>
    </div>
<?php endif; ?>
    <script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        }
    }
</script>
    <script type="text/x-magento-init">
    {
        ".js-quantity-selector": {
            "quantity-selector": {
                "increment": ".js-qty-plus",
                "decrement": ".js-qty-minus",
                "input": "#qty",
                "text": ".js-qty-text",
                "initialQty": <?php /* @escapeNotVerified */ echo $block->getProductDefaultQty() * 1 ?>
            }
        }
    }
</script>
<?php if (!$block->isRedirectToCartEnabled()) : ?>
    <script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "catalogAddToCart": {
                "bindSubmit": false
            }
        }
    }
</script>
<?php endif; ?>
